### ISSUE TITLE
BUG: Child frame container width

### ISSUE THREAD

**Issue by hobbes7878** [reuters-graphics/bluprint_graphics-rig#7]
Add this to style rules
```css
body.child-frame{
	    .container{
        width:100% !important;
        padding-left:0px;
        max-width:100% !important;
    }
}
```
